name: DeathChest
main: de.tobiyas.deathchest.DeathChest
version: 1.12
website: http://dev.bukkit.org/server-mods/deathchest/
author: Tobiyas
depend:
softdepend: [WorldGuard, LWC, Vault, PermissionsEx, GroupManager, PermissionsBukkit, SecureChests, Transporter]


description: >
             Fills a chest with your stuff, if you die.
commands:
  dcversion:
    description: displays the Version of DeathChest
    aliases: []
    usage: |
           /dcversion
  dcreload:
    description: reloads DeathChestConfig
    aliases: []
    usage: |
           /dcreload
  dchelp:
    description: help for DeathChest
    aliases: [deathchest]
    usage: |
           /dchelp
  dcpermcheck:
    description: permission Check for sender
    aliases: [dcpc]
    usage: |
           /dcpermcheck
  dcgravelist:
    description: lists all your GraveStones
    aliases: [dcgl]
    usage: |
           /dcgravelist
  dcport:
    description: ports to actual DeathChest
    aliases: [dcp]
    usage: |
           /dcport
  dcremove:
    description: removes DeathChest of Person in World.
    aliases: [dcr]
    usage: |
           /dcremove <playerName> <WorldName>
  dcgraveport:
    description: ports yourself to the GraveYard-Sign of the given player
    aliases: [dcgp]
    usage: |
           /dcgraveport number [PlayerName]